name: grec_minimal
description: A minimal parser/generator of recurrence rule for Google Calendar
version: 0.0.3
homepage: https://github.com/moznion/dart-grec-minimal
author: moznion <moznion@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dev_dependencies:
  test: ^1.5.1+1
